"""A1 M2 temporal-only variants over the sealed native-S1 RIFT frontend.

This module deliberately does not create an identity encoder or an E0 cache.
The caller supplies the native M2 ``TaskBank`` generated by the frozen S1
association-profile route.  All four arms therefore retain the same
proj_add-P16 frontend, carrier token channel, set decoder, source sampler, and
calibration bank.  Only position encoding and the temporal attention bias
change.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import log
from typing import Literal

import torch
from torch import Tensor, nn

from btransform_unified_v2.config import RiftTemporalConfig
from btransform_unified_v2.model import RiftDecoder
from btransform_unified_v2.streaming import RiftStreamDecoder
from btransform_unified_v2.temporal import RiftTemporal
from learnable_recency_v1.config import dataset_config
from learnable_recency_v1.temporal import LearnableRecencyState, LearnableRecencyTemporal


Arm = Literal["A_flat", "B_alibi", "C_learned", "D_alibi_plus_pe"]
ALIBI_SLOPES = tuple(2.0 ** (-8.0 * i / 8.0) for i in range(1, 9))


@dataclass(frozen=True)
class VariantSpec:
    arm: Arm
    use_sinusoidal_pe: bool
    bias: Literal["none", "fixed_alibi", "learned"]


SPECS: dict[Arm, VariantSpec] = {
    "A_flat": VariantSpec("A_flat", True, "none"),
    "B_alibi": VariantSpec("B_alibi", False, "fixed_alibi"),
    "C_learned": VariantSpec("C_learned", True, "learned"),
    "D_alibi_plus_pe": VariantSpec("D_alibi_plus_pe", True, "fixed_alibi"),
}


def sinusoidal_table(length: int, width: int, *, device: torch.device | None = None) -> Tensor:
    """Standard non-trainable sin/cos table with position zero at the session reset."""
    if length < 1 or width < 2 or width % 2:
        raise ValueError("sinusoidal PE requires positive length and even width >= 2")
    positions = torch.arange(length, dtype=torch.float32, device=device).unsqueeze(1)
    scales = torch.exp(torch.arange(0, width, 2, dtype=torch.float32, device=device) * (-log(10000.0) / width))
    table = torch.empty(length, width, dtype=torch.float32, device=device)
    table[:, 0::2] = torch.sin(positions * scales)
    table[:, 1::2] = torch.cos(positions * scales)
    return table


class A1Temporal(nn.Module):
    """Temporal facade compatible with ``RiftDecoder`` and ``RiftStreamDecoder``.

    The wrapped core remains the legacy local pre-LN transformer.  PE enters
    immediately before that core.  ``step`` uses the core state's per-stream
    positions, so its session reset semantics are exactly those of the
    existing streaming runtime.
    """

    def __init__(self, core: RiftTemporal, spec: VariantSpec) -> None:
        super().__init__()
        self.core = core
        self.spec = spec
        self.config = core.config
        self.register_buffer(
            "pe_scales",
            torch.exp(torch.arange(0, self.config.width, 2, dtype=torch.float32) * (-log(10000.0) / self.config.width)),
            persistent=True,
        )

    @property
    def recency_slopes(self) -> Tensor:
        return self.core.recency_slopes

    def set_attention_backend(self, backend: str) -> None:
        self.core.set_attention_backend(backend)

    def init_state(self, batch_size: int, device: torch.device | str, dtype: torch.dtype):
        return self.core.init_state(batch_size, device, dtype)

    def select_rows(self, state, row_indices):
        return self.core.select_rows(state, row_indices)

    def reset_rows(self, state, row_indices):
        return self.core.reset_rows(state, row_indices)

    def _positions(self, z: Tensor, absolute_positions: Tensor | None, valid_mask: Tensor | None) -> Tensor:
        if absolute_positions is None:
            return torch.arange(z.shape[1], device=z.device, dtype=torch.long).unsqueeze(0).expand(z.shape[0], -1)
        if absolute_positions.shape != z.shape[:2] or absolute_positions.dtype not in (torch.int32, torch.int64):
            raise ValueError("absolute_positions must be integer [batch,time]")
        positions = absolute_positions.to(device=z.device, dtype=torch.long)
        if valid_mask is not None and ((positions < 0) & valid_mask.to(device=z.device)).any():
            raise ValueError("negative absolute positions are permitted only for invalid left padding")
        return positions

    def _full_pe(self, z: Tensor, valid_mask: Tensor | None, absolute_positions: Tensor | None) -> Tensor:
        if not self.spec.use_sinusoidal_pe:
            return z
        positions = self._positions(z, absolute_positions, valid_mask)
        # Padding has no temporal meaning.  Clamp solely to form a safe lookup,
        # then zero the value before it reaches the temporal core.
        values = self._pe_values(positions.clamp_min(0), z.dtype)
        if valid_mask is not None:
            values = values * valid_mask.unsqueeze(-1).to(dtype=z.dtype)
        return z + values

    def _pe_values(self, positions: Tensor, dtype: torch.dtype) -> Tensor:
        angles = positions.to(dtype=torch.float32).unsqueeze(-1) * self.pe_scales.to(device=positions.device)
        values = torch.empty(*positions.shape, self.config.width, dtype=torch.float32, device=positions.device)
        values[..., 0::2] = torch.sin(angles)
        values[..., 1::2] = torch.cos(angles)
        return values.to(dtype=dtype)

    def forward(self, z: Tensor, valid_mask: Tensor | None = None, *, backend: str | None = None,
                absolute_positions: Tensor | None = None) -> Tensor:
        encoded = self._full_pe(z, valid_mask, absolute_positions)
        # C's local-batch and cached step paths can differ by accumulated
        # float32 reduction error after PE.  Evaluation intentionally follows
        # the cached recurrence exactly; training retains the vectorized local
        # kernel and is never used as a streaming-equivalence claim.
        if not self.training and self.spec.bias == "learned":
            mask = valid_mask if valid_mask is not None else torch.ones(z.shape[:2], dtype=torch.bool, device=z.device)
            state = self.core.init_state(z.shape[0], z.device, z.dtype)
            output = []
            for index in range(z.shape[1]):
                row, state = self.core.step(encoded[:, index], state, mask[:, index])
                output.append(row)
            return torch.stack(output, dim=1)
        return self.core(encoded, valid_mask, backend=backend)

    def step(self, z: Tensor, state, valid_mask: Tensor | None = None, *, absolute_positions: Tensor | None = None):
        if self.spec.use_sinusoidal_pe:
            pos = (torch.as_tensor(state.positions, dtype=torch.long, device=z.device)
                   if absolute_positions is None else absolute_positions.to(device=z.device, dtype=torch.long))
            if pos.shape != (z.shape[0],):
                raise ValueError("absolute_positions must be [batch]")
            effective_valid = (torch.ones(z.shape[0], dtype=torch.bool, device=z.device)
                               if valid_mask is None else valid_mask.to(device=z.device))
            if ((pos < 0) & effective_valid).any():
                raise ValueError("negative streaming position is permitted only for invalid left padding")
            values = self._pe_values(pos.clamp_min(0), z.dtype)
            z = z + values * effective_valid.unsqueeze(-1).to(dtype=z.dtype)
        return self.core.step(z, state, valid_mask)


def _fixed_core() -> RiftTemporal:
    # Geometry has no bearing on the initialized fixed slopes: it fixes M2 R50/D4.
    return RiftTemporal(RiftTemporalConfig.for_context(50, bias_mode="recency"))


def build_temporal(arm: Arm, *, seed: int) -> A1Temporal:
    """Build the requested arm without altering legacy package files.

    RIFT-only linear initialization is performed by ``RiftDecoder`` before
    this function replaces its temporal module; the caller transfers the
    initialized blocks through ``install_on_decoder`` below.
    """
    if arm not in SPECS:
        raise ValueError(f"unknown A1 arm {arm!r}")
    spec = SPECS[arm]
    core = _fixed_core()
    if spec.bias == "none":
        core.recency_slopes.zero_()
    elif spec.bias == "fixed_alibi":
        core.recency_slopes.copy_(torch.tensor(ALIBI_SLOPES, dtype=core.recency_slopes.dtype))
    else:
        cfg = dataset_config("m2", tier="learned_slope", layers=4, ladder="default")
        core = LearnableRecencyTemporal.from_initialized(core, cfg)
    core.set_attention_backend("local")
    return A1Temporal(core, spec)


def install_on_decoder(decoder: RiftDecoder, arm: Arm) -> RiftDecoder:
    """Swap temporal policy while preserving byte-identical non-temporal weights.

    The legacy decoder already owns deterministically initialized D4 blocks.
    We move those blocks into the new core rather than draw a new random
    initialization; this isolates the requested temporal factor.
    """
    old = decoder.temporal
    temporal = build_temporal(arm, seed=decoder.seed).to(next(decoder.parameters()).device)
    temporal.core.blocks = old.blocks
    # ``LearnableRecencyTemporal`` has no need for the old fixed slope buffer;
    # its constructor initialized the declared half-life slopes and increments.
    decoder.temporal = temporal
    decoder.temporal_config = temporal.config
    decoder.bias_mode = SPECS[arm].bias
    return decoder


class A1M2Decoder(RiftDecoder):
    """RIFT decoder with an explicit session-coordinate PE contract."""

    def forward_scores(self, x: Tensor, bank, unit_mask=None, dropout_generator=None, dropout_keep=None,
                       input_valid_mask: Tensor | None = None, *, absolute_positions: Tensor | None = None) -> Tensor:
        x = self._check_input(x, input_valid_mask)
        if input_valid_mask is not None:
            x = torch.where(input_valid_mask.unsqueeze(-1), x, torch.zeros_like(x))
        z = self.frontend_tokens(x, bank, unit_mask, dropout_generator, dropout_keep)
        hidden = self.temporal(z, input_valid_mask, absolute_positions=absolute_positions)
        return self.readout(self.final_norm(hidden))

    def forward(self, x: Tensor, bank, unit_mask=None, dropout_generator=None, dropout_keep=None,
                input_valid_mask: Tensor | None = None, *, absolute_positions: Tensor | None = None) -> Tensor:
        return self.forward_scores(x, bank, unit_mask, dropout_generator, dropout_keep, input_valid_mask,
                                   absolute_positions=absolute_positions)[:, -1]


class A1M2StreamDecoder(RiftStreamDecoder):
    """Streaming adapter which retains C's learned increment caches on pack."""

    def _pack_states(self, states: list):
        packed = super()._pack_states(states)
        core = self.decoder.temporal.core
        if not isinstance(core, LearnableRecencyTemporal):
            return packed
        if not isinstance(packed, LearnableRecencyState):
            raise TypeError("A1 learned temporal did not create LearnableRecencyState")
        if any(not isinstance(state, LearnableRecencyState) for state in states):
            raise TypeError("A1 learned temporal stream state drift")
        packed.increments = [
            [list(state.increments[layer][0]) for state in states]
            for layer in range(self.decoder.temporal_config.layers)
        ]
        return packed


def build_decoder(arm: Arm, *, seed: int = 42, proj_dim: int = 16) -> A1M2Decoder:
    decoder = A1M2Decoder("m2", context_bins=50, bias_mode="recency", seed=seed, proj_dim=proj_dim)
    decoder = install_on_decoder(decoder, arm)
    if tuple(decoder.temporal.config.windows) != (13, 12, 12, 12):
        raise RuntimeError("A1 M2 temporal window contract drift")
    return decoder


def contract(arm: Arm) -> dict[str, object]:
    spec = SPECS[arm]
    return {
        "arm": arm,
        "sinusoidal_pe": spec.use_sinusoidal_pe,
        "bias": spec.bias,
        "fixed_slopes": list(ALIBI_SLOPES) if spec.bias == "fixed_alibi" else ([0.0] * 8 if spec.bias == "none" else None),
        "learned_initialization": "existing default half-life ladder, per-layer" if spec.bias == "learned" else None,
        "context_bins": 50,
        "layer_windows": [13, 12, 12, 12],
        "width": 256,
        "heads": 8,
    }
